apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: omni-secret-static-sync
  namespace: omni
spec:
  infisicalAuthRef:
    name: omni-infisical-auth
    namespace: omni

  syncOptions:
    refreshInterval: 5m

  sources:
    - projectSlug: bayesian-credit-ig-zb
      environmentSlug: prod
      secretPath: /omni

  targets:
    - name: omni-secret
      namespace: omni
      kind: Secret
      creationPolicy: Owner
