ingress:
  main:
    enabled: false
  kubernetesProxy:
    enabled: false
  siderolinkApi:
    enabled: false

config:
  account:
    name: "Data And Engineering"
    id: "a3e89f21-72b1-4c1d-8422-92a8310c8f12"

  auth:
    auth0:
      enabled: false
      # Match the parent section where oidc: resides in your default_values.yaml
    oidc:
      enabled: true
      providerURL: "https://identity.sazara.co.ke/application/o/talos-omni/"
      clientID: "talos-omni"
      clientSecret: ""
      scopes: ["openid", "profile", "email"]
      logoutURL: "https://identity.sazara.co.ke/application/o/talos-omni/end-session/"
    initialUsers:
      - "mistidevs@gmail.com"

  services:
    api:
      advertisedURL: "https://omni.sazara.co.ke"
    kubernetesProxy:
      advertisedURL: "https://omni-k8s.sazara.co.ke"
    machineAPI:
      advertisedURL: "https://omni-siderolink.sazara.co.ke"
    siderolink:
      wireGuard:
        advertisedEndpoint: "167.172.10.114:30180"



envFrom:
  - secretRef:
      name: omni-secret

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
