ingress:
  main:
    enabled: false
  kubernetesProxy:
    enabled: false
  siderolinkApi:
    enabled: false

config:
  account:
    name: "Data And Engineering"
    id: "a3e89f21-72b1-4c1d-8422-92a8310c8f12"

  auth:
    auth0:
      enabled: false
    saml:
      enabled: true
      url: "https://identity.sazara.co.ke/application/saml/talos-omni/metadata/"
      nameIDFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

      attributeRules:
        identity: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
        fullname: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
        firstname: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"
        lastname: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"

      labelRules:
        "omni.sidero.dev/role": "http://schemas.xmlsoap.org/claims/Group"
    initialUsers:
      - "mistidevs@gmail.com"

  services:
    api:
      advertisedURL: "https://omni.sazara.co.ke"
    kubernetesProxy:
      advertisedURL: "https://omni-k8s.sazara.co.ke"
    machineAPI:
      advertisedURL: "https://omni-siderolink.sazara.co.ke"
    siderolink:
      wireGuard:
        advertisedEndpoint: "167.172.10.114:30180"

envFrom:
  - secretRef:
      name: omni-secret

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
